#!/bin/sh
set -e

manpages=$(dpkg -L libncurses-dev:"$(dpkg --print-architecture)" ncurses-bin ncurses-doc \
	    | grep ^/usr/share/man/man./)

echo "Checking for broken manpage references ..."
for manpage in $manpages ; do
    if [ -f "$manpage" ] && [ ! -L "$manpage" ] ; then
	zgrep -nH '(3X)' "$manpage" 1>&2 || true
    fi
done
